---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: name-tests-test
        files: ^.*\/test\/.*$
        args: [--pytest-test-first]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        entry: codespell

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        files: ^(?!.*compose).*$
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '100']

    # Docs - RestructuredText hooks
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        args: [--max-line-length=100, --ignore=D001]
        exclude: ^.*\/CHANGELOG\.rst/.*$
