services:
  navigation:
    image: husarion/navigation2:humble-1.1.3
    container_name: navigation
    network_mode: host
    ipc: host
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
      - ./maps:/maps
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}
        map:=/maps/map.yaml
