services:
  pointcloud_to_laserscan:
    image: husarion/navigation2:humble-1.1.3-20230127
    container_name: pointcloud_to_laserscan
    network_mode: host
    ipc: host
    command: >
      ros2 run pointcloud_to_laserscan pointcloud_to_laserscan_node 
        --ros-args 
        -r cloud_in:=${POINTCLOUD2_TOPIC:-velodyne_points}