services:
  panther_gazebo:
    image: husarion/panther-gazebo:humble-ros2-devel
    container_name: panther_gazebo
    network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config:/config
    command: >
      ros2 launch panther_gazebo simulation.launch.py
      components_config_path:=/config/components.yaml
