services:
  mapping:
    image: husarion/slam-toolbox:humble-2.6.3
    container_name: mapping
    network_mode: host
    ipc: host
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  map-saver:
    image: husarion/nav2-map-server:humble-1.1.3
    container_name: map_saver
    network_mode: host
    ipc: host
    volumes:
      - ./maps:/maps
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"
