services:
  ros1_bridge:
    image: ros:galactic-ros1-bridge
    container_name: ros-bridge
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.3
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: ros2 run ros1_bridge dynamic_bridge
