services:
  panther_gazebo:
    image: husarion/panther:noetic-simulation
    container_name: panther_gazebo
    network_mode: host
    runtime: nvidia
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./simulation/panther_willowgarage.launch:/ros_ws/src/panther_gazebo/launch/panther_willowgarage.launch
      - ./simulation/urdf/panther_velodyne.urdf.xacro:/ros_ws/src/panther_description/urdf/panther.urdf.xacro
    command: roslaunch panther_gazebo panther_willowgarage.launch

  webui-ros-joystick:
    image: husarion/webui-ros-joystick:noetic
    container_name: webui-ros-joystick
    network_mode: host
    command: roslaunch webui-ros-joystick panther_webui.launch --wait

  ros1_bridge:
    image: ros:galactic-ros1-bridge
    container_name: ros-bridge
    network_mode: host
    ipc: host
    command: ros2 run ros1_bridge dynamic_bridge
